underlay:
    local:
        asn: 60012
    neighbors:
      - interface: em3
        name: SPINE01
        asn: 60001
        peer_ip: 171.0.0.4
        local_ip: 171.0.0.5
      - interface: em4
        name: SPINE02
        asn: 60002
        peer_ip: 171.0.0.6
        local_ip: 171.0.0.7
